apiVersion: v1
kind: Secret
metadata:
  name: twitch-bot-secret
type: Opaque
data:
  bot-nickname: dHdpdGNoX2JvdA==  # base64 encoded "twitch_bot"
  tmi-token: b2F1dGg6dXN2Z2NpbWQzZ3czNDl2NDV6aHQ1dWVrZ2Jmem43  # base64 encoded "oauth:usvgcimd3gw349v45zht5uekgbfzn7" 