apiVersion: v1
kind: ConfigMap
metadata:
  name: twitch-bot-pandabotconnect-config
data:
  channel: "pandabotconnect"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: twitch-bot-pandabotconnect
  labels:
    app: twitch-bot
    channel: pandabotconnect
spec:
  replicas: 1
  selector:
    matchLabels:
      app: twitch-bot
      channel: pandabotconnect
  template:
    metadata:
      labels:
        app: twitch-bot
        channel: pandabotconnect
    spec:
      containers:
      - name: twitch-bot
        image: twitch-bot:latest
        imagePullPolicy: Never
        args: ["--channel", "$(CHANNEL_NAME)"]
        env:
        - name: CHANNEL_NAME
          valueFrom:
            configMapKeyRef:
              name: twitch-bot-pandabotconnect-config
              key: channel
        - name: TWITCH_TMI_TOKEN
          valueFrom:
            secretKeyRef:
              name: twitch-bot-secret
              key: tmi-token
        - name: MONGODB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-credentials
              key: password
        - name: MONGODB_USER
          value: "TwitchBot"
        - name: MONGODB_HOST
          value: "mongodb"
        - name: MONGODB_PORT
          value: "27017"
        ports:
        - containerPort: 8080
          name: health
        livenessProbe:
          httpGet:
            path: /health
            port: health
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: health
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        volumeMounts:
        - name: logs
          mountPath: /app/logs
      volumes:
      - name: logs
        emptyDir: {} 